### ISSUE TITLE
Porblems about gimbal calibration

### ISSUE THREAD

**Issue by kidzrl** [RoboMaster/RoboRTS-Firmware#1]
Hello there. This is a really nice code. However, I met a issue about gimbal calibration. I followed the 
 four steps in 'Gimbal calibration method' which was mentioned in the 'readme.txt' , first , I turned the remote control levers to gimbal disabled position and infantry powered on , and I ran the program , the codes ran into the function called 'no_cali_data_handle()', then goes into the gimbal_cali_msg_hook() ,  but it never goes into' if ((last_type == GIMBAL_CALI_START) && (cur_type == GIMBAL_CALI_END))' branches.  How can I set up these two types? And I cannot find a variable called cali_param.Gimbal.cali_cmd, just found cali_param_data.cali_cmd , and I set it to 1, It returned nothing , and every variables were 0xFF. So I cannot calibration my gimbal motors correctly. By the way , I uses 6623 motors as gimbal motors. I'm looking forward for your reply.  Thanks.

**Comment by eeluobu** [comment]
The calibration method in'readme.txt' is a legacy problem, this version is no longer used, and you can use the protocol to calibrate gimbal through tx1/2 or pc send correct cmd, the command id is 0x00A5

**Comment by kidzrl** [comment]
Thank you for your reply. Does it means in this version I just need to handle the gimbal to the midpoint , then send the command ID to the RM board , and everything will be OK. And it's not necessary to use J-link and MDK debugger?

**Comment by sujunyan** [comment]
Yes, I am also confused about the calibration method in'readme.txt'.
Maybe youcan update it or simpily delete it.

**Comment by Mor-harry** [comment]
@kidzrl @sujuanyan 在你们连接好系统后（包括裁判系统和PC接口还有黑色的陀螺仪），之后进入Debug就可以在watch下进行参数设置，你要在cali_param下进行参数的设置。
