### ISSUE TITLE
What is a good way to debug RTOS? 

### ISSUE THREAD

**Issue by AK51** [RoboMaster/RoboRTS-Firmware#13]
Breakpoint and watch window do not really work, may I know what is a typical way to debug a rtos program? Thx

**Comment by bzrobotics** [comment]
we suggest that you connect PC xshell software and development board usart6 via usb to TTL tool and use ulog. it is a rt-thread logging component.

**Comment by AK51** [comment]
Is there any quick tutorial or video I can follow?
We tried to run your code in our robot but it stopped at some initialization... we can just use the LED blink to guess where it stops...
I saw in the code that I can damp all parameter out, how to saw all variable?
Sorry, I am new to RTOS. Is there any good link for me to pick up fast? Thx

**Comment by bzrobotics** [comment]
rtos: https://www.keil.com/pack/doc/CMSIS/RTOS/html/group__CMSIS__RTOS.html
ulog: https://www.rt-thread.org/document/site/programming-manual/ulog/ulog/
mdk: http://www2.keil.com/mdk5/docs
Please provide the team name and contact details. and do you need an English readme? we provide it as soon as possible.

**Comment by AK51** [comment]
How can I send a private message? Github blocked it I think... Btw, I can read Chinese. Thx

**Comment by bzrobotics** [comment]
email: robomaster@dji.com

**Comment by AK51** [comment]
「curtaihvyn <notifications@github.com>」在 2019年3月4日 週一，下午7:26 寫道：

**Comment by AK51** [comment]
「Andy Kong <andykong51@gmail.com>」在 2019年3月5日 週二，上午10:06 寫道：

**Comment by bzrobotics** [comment]
ok，已经有相关人员发送好友申请，我们可以通过微信解答

**Comment by JorgePerC** [comment]
> rtos: https://www.keil.com/pack/doc/CMSIS/RTOS/html/group__CMSIS__RTOS.html
> ulog: https://www.rt-thread.org/document/site/programming-manual/ulog/ulog/
> mdk: http://www2.keil.com/mdk5/docs
> Please provide the team name and contact details. and do you need an English readme? we provide it as soon as possible.

Hello There, I don't know how to read chinese would it be too much to ask for a readme in english? 
thanks in advance :)

Jorge Pérez: jorgeperez_1@live.com from Telpochcalli :)
