### ISSUE TITLE
Is the communication protocol on master branch backward-compatible?

### ISSUE THREAD

**Issue by shwnyao** [RoboMaster/RoboRTS-Firmware#14]
We are trying to communicate between the STM32 and TX2. We found out that the protocol in RoboRTS-Firmware documentation is 1.3, but the one on master and dev branches are still 1.0. Can it just work out-of-the-box? Or how do we make modifications?

**Comment by shwnyao** [comment]
And actually, even if we update to V1.3, is it gonna work with RoboRTS?

**Comment by bzrobotics** [comment]
You don't need any changes if you use the latest code. you should switch icra2019_dev branch.
