### ISSUE TITLE
Can the source code be used to drive the car directly?

### ISSUE THREAD

**Issue by stephenxin** [RoboMaster/RoboRTS-Firmware#2]
I have trid to drive the car with RoboRTS-Firmware,but I failed anyway.now,I have recovered the macro definition of “#define AUTO_NAVIGATION” in sys_config.h ,and I found in function "can_msg_send_task" ,"send_chassis_motor_ctrl_message(glb_cur.chassis_cur)" has been executed successed when the value of glb_cur.chassis_cur are not zero and can be changed by remote control , but four mecanum wheels just won't move.I have checked  several documents about this,but I didn't found any solution，is there anything I need to do or something maybe I forgot?
I know it might be a stupid question，but I really don't know what to do now,any suggestion would be appreciated,thanks in advanced.

**Comment by Mor-harry** [comment]
@stephenxin 你应该讲裁判系统还有黑色的陀螺仪连接到硬件中，否则系统无法运行。要么就需要去注释掉这些error和裁判系统的限制

**Comment by eeluobu** [comment]
We updated the project description and protocol documents, may be helpful to you. And we will release the upper debug interface code as soon as possible in RoboRTS.

**Comment by stephenxin** [comment]
@eeluobu got it ,thank you!

**Comment by lyziew** [comment]
@349141450 黑色陀螺仪是什么型号

**Comment by Mor-harry** [comment]
@lyziew  RM前几年送的车里有一个黑色的单轴陀螺仪，ADI的片子，你可以从RM最新的购买清单里看到
