### ISSUE TITLE
robomasterC型开发板刷固件的问题

### ISSUE THREAD

**Issue by gongpx20069** [RoboMaster/RoboRTS-Firmware#25]
robomasterC型开发板的型号是407，而Firmware中给的程序型号是427，当device中芯片型号改成407后会报错，请问怎么解决？初此参赛，请多指教
<img width="955" alt="报错截图" src="https://user-images.githubusercontent.com/21985921/72235547-c1ac7100-360d-11ea-9ca3-f820ee965d80.png">
<img width="480" alt="修改芯片型号" src="https://user-images.githubusercontent.com/21985921/72235548-c1ac7100-360d-11ea-8976-862408093f0f.png">

**Comment by bzrobotics** [comment]
icra2020 Firmware已经正式更新，请刷写branch icra2020分支代码。icra2019分支为19年官方平台固件，硬件有所不同。可自由选择刷写armcc或gcc版本固件。

**Comment by gongpx20069** [comment]
我们昨天在使用RoboRTS测试代码的时候，发现其中一些topic有传感器的数据，请问2020官方车是否已经刷好了固件呢？

**Comment by bzrobotics** [comment]
官方车发车之前已经完成固件刷写

**Comment by gongpx20069** [comment]
感激

**Comment by gongpx20069** [comment]
close这个issue吧
