### ISSUE TITLE
The Gimbal Problem

### ISSUE THREAD

**Issue by kidzrl** [RoboMaster/RoboRTS-Firmware#4]
Hello. I met a problem during my development. I calibrated two motors of the gimbal, and they made a success initial and both of them back to the center. However, the motors will become dramatic shaking after about five minutes power off, at this moment if we restart the power quickly, the gimbal will back to normal and we can take a good control of it. Is this a bug or just we made any mistake. Some other teams said they met the same problem when we communicate with each other. Looking forward for your reply. Thanks.

**Comment by eeluobu** [comment]
After calibrating the gimbal, you should restart the power

**Comment by Lzhigang** [comment]
万向节电机是云台电机吗

**Comment by kidzrl** [comment]
是的

**Comment by kidzrl** [comment]
@eeluobu I tried that, but this problem is still happening.

**Comment by eeluobu** [comment]
@kidzrl Try the latest program on master branch
