### ISSUE TITLE
How to control the motor by remote?

### ISSUE THREAD

**Issue by laphets** [RoboMaster/RoboRTS-Firmware#5]
Sorry to raise such seemingly stupid question. However, we have read the code from freertos.c, remote_ctrl.c to chassis_task.c, we still couldn't find the way to control the motor by remote. And we also find code in chassis_task.c never runs, which obsesses me a lot. Still waiting for help...

**Comment by eeluobu** [comment]
The motor of chassis and gimbal is controlled by the CAN bus, and you can learn how to drive it by reading the corresponding instructions.
gimbal motor link: [https://www.robomaster.com/zh-CN/products/components/detail/131](https://www.robomaster.com/zh-CN/products/components/detail/131)
chassis motor link: [https://www.robomaster.com/zh-CN/products/components/detail/142](https://www.robomaster.com/zh-CN/products/components/detail/142)
