### ISSUE TITLE
云台电机错误

### ISSUE THREAD

**Issue by 690590620** [RoboMaster/RoboRTS-Firmware#7]
当我把程序下进去后，开始提示云台电机（Y或P轴电机）离线，当我用其他程序时，云台电机是能正常工作的，说明云台通信良好，请问想这是什么原因？感谢

**Comment by Lzhigang** [comment]
我也是这样的问题

**Comment by Mor-harry** [comment]
你们没有仔细阅读文档，需要对云台进行校准，并且链接裁判系统和tx2的串口

**Comment by 690590620** [comment]
我用了ST_LINK进行校准，当云台在正中间时将变量cali_param.gim_cali_data[].cali_cmd设为1，但还是没能成功然后继续运行该程序，并不能使云台维持在中间，是校准方法错了吗？

**Comment by eeluobu** [comment]
@690590620 If you do not use single gyroscope module in chassis, need to close gyro_device_init() in main.c, otherwise it will affect CAN-BUS and cause the motor off-line.
