### ISSUE TITLE
The data of yaw of imu is always changing bigger or smaller  

### ISSUE THREAD

**Issue by jungleooo** [RoboMaster/RoboRTS-Firmware#8]
Hello. I met a problem during my development. I saw the data of imu, and I found that the data of yaw of imu is always changing bigger. But the data of pitch and rol is stable. I wonder did other team met this problem either. Is this a bug or just we made any mistake. Looking forward for your reply. Thanks.

**Comment by eeluobu** [comment]
If you enable magnetometer of imu the yaw angle will be stable, but this imu data is easy to be disturbed by external environment, as: motor, magnet etc.
The 218 line of bsp_imu.c can enable magnetometer.
