### ISSUE TITLE
old version board && new version Firmware 

### ISSUE THREAD

**Issue by RangooDu** [RoboMaster/RoboRTS-Firmware#9]
hello, @KevinLADLee @robomasterbot ,I bought the infantry car in 2018.1 which used the old version board,but the RoboRTS-Firmware is based on the new type board(Type A). I have  compared the schematics,there were some differences between them ,the main different was the IMU,can new firmware work in old version board? Do you have the firmware based on old version board?

**Comment by eeluobu** [comment]
The RoboRTS-Firmware tags of 'old_board' is old version RM board, but maybe incompatible with the latest RoboRTS code. And the old board has been discontinued, we suggest using the new development board.

**Comment by KevinLADLee** [comment]
@Wangergou123  [Old Version Tag](https://github.com/RoboMaster/RoboRTS-Firmware/tree/old_board)

Tips: First, personally I think you should learn more about how to use `git`. And if you really want to develop some projects based on this repo, you should know how to develop program on STM32. Differences between old board and new board could be solved very easy if you have some experience on embedded system development.
